---
-
  hosts: database
  sudo: true
  tasks:
    -
      apt: "name=mysql-server state=present update_cache=yes"
      name: "install mysql server"
    -
      name: "ensure mysql started and working as expected"
      service: "name=mysql state=started enabled=yes"
