---
-
  become: true
  hosts: tag_Name_loadbalancer_database
  tasks:
    -
      service: "name=nginx state=stopped"
-
  hosts: tag_Name_webserver
  become: true
  tasks:
    -
      service: "name=apache2 state=stopped"
-
  hosts: tag_Name_loadbalancer_database
  become: true
  tasks:
    -
      service: "name=mysql state=restarted"
-
  hosts: tag_Name_webserver
  become: true
  tasks:
    -
      service: "name=apache2 state=started"
-
  hosts: tag_Name_loadbalancer_database
  become: true
  tasks:
    -
      service: "name=nginx state=started"
