---
-
  hosts: loadbalancer
  sudo: true
  tasks:
    -
      service: "name=nginx state=stopped"
-
  hosts: webserver
  sudo: true
  tasks:
    -
      service: "name=apache2 state=stopped"
-
  hosts: database
  sudo: true
  tasks:
    -
      service: "name=mysql state=restarted"
-
  hosts: webserver
  sudo: true
  tasks:
    -
      service: "name=apache2 state=started"
-
  hosts: loadbalancer
  sudo: true
  tasks:
    -
      service: "name=nginx state=started"
