---
-
  hosts: webserver
  sudo: true
  tasks:
    -
      apt: "name={{item}} state=present update_cache=yes"
      name: "install webserver dependencies"
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
    -
      name: "ensure apache2 started and working as expected"
      service: "name=apache2 state=started enabled=true"
