---
-
  become: true
  handlers:
    -
      name: "restart apache2"
      service: "name=apache2 state=restarted"
  hosts: webserver
  tasks:
    -
      apt: "name={{item}} state=present update_cache=yes"
      name: "install webserver dependencies"
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
        - python-mysqldb
    -
      name: "ensure apache2 started and working as expected"
      service: "name=apache2 state=started enabled=true"
    -
      apache2_module: "state=present name=wsgi"
      name: "ensure mod_wsgi is enabled"
      notify: "restart apache2"
    -
      copy: "src=demo/app/ dest=/var/www/demo mode=0755"
      name: "copy demo app source"
      notify: "restart apache2"
    -
      copy: "src=demo/demo.conf dest=/etc/apache2/sites-available"
      name: "copy apache virtual host config"
      notify: "restart apache2"
    -
      name: "setup python virtualenv"
      notify: "restart apache2"
      pip: "requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv"
    -
      file: "path=/etc/apache2/sites-enabled/000-default.conf state=absent"
      name: "de-activate default apache site"
      notify: "restart apache2"
    -
      file: "src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link"
      name: "activate demo site"
      notify: "restart apache2"
