---
-
  sudo: yes
  hosts: webserver
  tasks:
    -
      apt: "name={{item}} state=present update_cache=yes"
      name: "install webserver dependencies"
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
